#! /bin/bash
user=$(logname)
PATH_TO_DIRSEARCH="/home/$user/Desktop/"
shadow_theme() {
  echo """
-!-!-!-!-!-!-!-!-!-!-!-!-!- by Moatuz -!-!-!-!-!-!-!-!-!-!-!-!-!-

              ! SHADOW RECON !

            █▓▒▓█▀██▀█▄░░▄█▀██▀█▓▒▓█
            █▓▒░▀▄▄▄▄▄█░░█▄▄▄▄▄▀░▒▓█
            █▓▓▒░░░░░▒▓░░▓▒░░░░░▒▓▓█
            

-!-!-!-!-!-!-!-!-!-!-!-!-!- auto recon tool -!-!-!-!-!-!-!-!-!-!-!-!-!- 
"""

}

nmap_scan() 
{
  if [ -n "$DOMAIN" ]; then
    nmap $DOMAIN > "$DIRECTORY/nmap"
    echo "The result of the nmap scan is stored in $DIRECTORY/nmap"
  else
    echo "Error: DOMAIN variable is not set"
  fi
}

dirsearch_scan() 
{
  if [ -n "$DOMAIN" ];then 
    $PATH_TO_DIRSEARCH/dirsearch.py -u "$DOMAIN" -e php --output "$DIRECTORY/dirsearch.txt"
    echo "the result of dirsearch scan are stored in $DIRECTORY/dirsearch.txt"
  fi
}

crt_scan() 
{
  shadow_theme
  if [ -n "$DOMAIN" ]; then
    curl "https://crt.sh/?q=$DOMAIN&output=json" -o "$DIRECTORY/crt"
    echo "the result of cert parsing is stored in $DIRECTORY/crt"
  fi
}
